config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }

  namespace :api do
    namespace :v1 do
      resources :monsters, except: [:new, :edit]
      resources :teams
    end
  end

  root 'home#index'
  resources :monsters
  resources :teams

end

app/models/monster.rb
class Monster < ActiveRecord::Base
  belongs_to :user
  belongs_to :team

  validates :name, presence: true, uniqueness: {scope: :user_id}
  validates :user_id, presence: true
  validates :power, presence: true
  validates :monster_type, presence: true, inclusion: {in: %w(fire water earth electric wind)}
  validate :available_monsters, on: :create
  validate :team_size

  private

  def team_size
    if team && !team.allows_new_monster?
      errors.add(:base, 'Team size limit exceeded')
    end
  end

  def available_monsters
    unless user.allows_new_monster?
      errors.add(:base, 'Reached the number of monsters')
    end
  end
end

app/controllers/api/v1/monsters_controller.rb
module Api
  module V1
    class MonstersController < ApplicationController
      skip_before_filter :verify_authenticity_token
      respond_to :json

      def index
        respond_with Monster.all
      end

      def show
        monstor =  Monster.find(params[:id])
        render(json: monstor)
      end

      def create
        respond_with Monster.create(monster_params)
      end

      def update
        respond_with Monster.update(params[:id], params[:monsters])
      end

      def destroy
        respond_with Monster.destroy(params[:id])
      end

      private
      def monster_params
        params.require(:monster).permit(:name, :monster_type, :power, :user_id, :team_id)
      end
    end
  end
end

app/controllers/monsters_controller.rb
class MonstersController < ApplicationController
  helper_method :sort_column, :sort_direction
  before_action :set_monster, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!

  # GET /monsters
  # GET /monsters.json
  def index
    @monsters = current_user.monsters.order(sort_column + " " + sort_direction)
    @count = 20 - current_user.monsters.count
    @teams = current_user.teams
    @teams_count = 3 - @teams.count
  end

  # GET /monsters/1
  # GET /monsters/1.json
  def show
  end

  # GET /monsters/new
  def new
    @monster = Monster.new
  end

  # GET /monsters/1/edit
  def edit
  end

  # POST /monsters
  # POST /monsters.json
  def create
    @monster = current_user.monsters.new(monster_params)

    respond_to do |format|
      if @monster.save
        format.html { redirect_to @monster, notice: 'Monster was successfully created.' }
        format.json { render :show, status: :created, location: @monster }
      else
        format.html { render :new }
        format.json { render json: @monster.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /monsters/1
  # PATCH/PUT /monsters/1.json
  def update
    respond_to do |format|
      if @monster.update(monster_params)
        format.html { redirect_to @monster, notice: 'Monster was successfully updated.' }
        format.json { render :show, status: :ok, location: @monster }
      else
        format.html { render :edit }
        format.json { render json: @monster.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /monsters/1
  # DELETE /monsters/1.json
  def destroy
    @monster.destroy
    respond_to do |format|
      format.html { redirect_to monsters_url, notice: 'Monster was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_monster
      @monster = Monster.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def monster_params
      params.require(:monster).permit(:name, :monster_type, :power, :team_id)
    end

    def sort_column
      Monster.column_names.include?(params[:sort]) ? params[:sort] : 'name'
    end

    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : 'asc'
    end
end

app/helpers/monsters_helper.rb
module MonstersHelper
  def sortable(column, title = nil)
    title ||= column.titleize
    css_class = column == sort_column ? "current #{sort_direction}" : nil
    direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
    link_to title, {:sort => column, :direction => direction}, {:class => css_class}
  end
end

app/views/monsters/_form.html.erb
<%= form_for(monster) do |f| %>
  <% if monster.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(monster.errors.count, "error") %> prohibited this monster from being saved:</h2>

      <ul>
      <% monster.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group col-md-8">
    <%= f.text_field :name, placeholder: 'Name', class: 'form-control' %>
  </div><br />

  <div class="form-group col-md-8">
    <%= f.text_field :power, placeholder: 'Power', class: 'form-control' %>
  </div><br />

  <div class="form-group col-md-8">
    <%= f.select :monster_type, [['Fire','fire'],['Water','water'],['Earth','earth'], ['Electric', 'electric'], ['Wind', 'wind']] %>
  </div><br />

  <div class="form-group col-md-8">
    <%= f.submit %>
  </div>
<% end %>

app/views/monsters/edit.html.erb
<h1>Editing Monster</h1>

<%= render 'form', monster: @monster %>

<%= link_to 'Show', @monster %> |
<%= link_to 'Back', monsters_path %>

app/views/monsters/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Monsters</h1>

<%= @teams_count %> teams remaining
<br />
<%= link_to button_tag('Create a team', class: 'btn btn-default'), new_team_path unless current_user.teams.count >= 3 %>
<br /><br />

<% if @teams.any? %>
  <% for team in @teams %>
    <div class="well">
      <p><%= team.name %></p>
      <% team.monsters.each do |monster| %>
        <li><%= monster.name %></li>
      <% end %>
    </div>
  <% end %>
<% end %>

<%= @count %> monsters remaining
<br /><br />

<table class='pretty'>
  <thead>
    <tr>
      <th><%= sortable "name", "Name" %></th>
      <th><%= sortable "power", "Power" %></th>
      <th><%= sortable "monster_type", "Monster Type" %></th>
    </tr>
  </thead>

  <tbody>
    <% @monsters.each do |monster| %>
      <tr>
        <td><%= monster.name %></td>
        <td><%= monster.power %></td>
        <td><%= monster.monster_type %></td>
        <td><%= link_to 'Show', monster %></td>
        <td><%= link_to 'Edit', edit_monster_path(monster) %></td>
        <td><%= link_to 'Destroy', monster, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Add New Monster', new_monster_path unless current_user.monsters.count >= 20 %> |
<%= link_to 'View Teams', teams_path %>

app/views/monsters/new.html.erb
<h1>New Monster</h1>

<%= render 'form', monster: @monster %>

app/views/monsters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @monster.name %>
</p>

<p>
  <strong>Power:</strong>
  <%= @monster.power %>
</p>

<p>
  <strong>Type:</strong>
  <%= @monster.monster_type %>
</p>

<%= link_to 'Edit', edit_monster_path(@monster) %> |
<%= link_to 'Back', monsters_path %>